version: "3.8"

services:
  fastapi:
    build: ./app
    container_name: ww-be
    restart: always
    ports:
      - "1885:8000"
    env_file:
      - .env
    depends_on:
      - ww-mongodb

  mongodb:
    image: mongo:6.0
    container_name: ww-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
